### PR TITLE
Update hectime.pyx for changing 24 hour to 23 hour

### PR DESCRIPTION
**Pull request by HydroSynapseKR**
Not really sure if this is what is meant but on line 155 trying to convert 24:00:00 to 23:00:00 does not look right.

### CODE REVIEW

**Comment by gyanz** [comment]
@KushalMBI You are right. Can you please rename the variable `_timestring_temp` as `temp`?

**Comment by HydroSynapseKR** [comment]
> @KushalMBI You are right. Can you please rename the variable `_timestring_temp` as `temp`?

Removed that variable entirely. performed the string conversion on a single line directly.

**Comment by danhamill** [comment]
What are the implications of this change?

**Comment by mxkpp** [comment]
> What are the implications of this change?

I am also curious about this.  Have there been any cases identified where this could break existing implementations of the lib?

**Comment by HydroSynapseKR** [comment]
> > What are the implications of this change?
> 
> I am also curious about this. Have there been any cases identified where this could break existing implementations of the lib?

It should not break what was already working. It is just time formatting correction. I haven't run into issues with the implementation of this update.

**Comment by MikeNeilson** [comment]
It's possible this change isn't actually correct.
It's setting the time to 2300 hours. The proper "correction" so that things like python's `datetime` library can process that instant in time correctly would be 0000 the next day.

The usage of 2400 is quirk of how USACE identified data that applies to "end of day" vs "beginning of day". Not as critical for instantaneous values but a fairly important distinction for things like averages.

**Comment by HydroSynapseKR** [comment]
> It's possible this change isn't actually correct. It's setting the time to 2300 hours. The proper "correction" so that things like python's `datetime` library can process that instant in time correctly would be 0000 the next day.
> 
> The usage of 2400 is quirk of how USACE identified data that applies to "end of day" vs "beginning of day". Not as critical for instantaneous values but a fairly important distinction for things like averages.

The 1 hour difference is added back. 2400 is changed to 2300 so that it can be properly converted to python datetime object and the parameter is_24hr is set to True, then in 168, it is checked if the 2400 was changed to 2300 (by checking if is_24hr is True) and then 1 hour is added back.

**Comment by MikeNeilson** [comment]
It's not super clear from the code but it's that's just happening so a datetime can be rendered, and the 24 manually add back in to the resulting string than this tweak is fine and you can ignore what follows.

Otherwise the tweak is wrong.
`01AUG2017 2400` in USACE time is equivalent to `02Aug2017 0000` in sane time libraries.

If you start doing a lot of manual with the time converted to 23 it's going to get really wonky. And awkward with all the checks for is "24". 

The way I've handled in the past is to have a %K in place of %H, as I've seen it used in some libraries) for the format string and use that to decide to render the 2400 value, but otherwise the datetime objects are kept with actual standard time ranges.

Instead of keeping track of is_24hr it would make more sense to track "is end of period", which is the default for anything out of DSS, but within python to force the times to be normal times

**Comment by danhamill** [comment]
I have found the method to subtract an hour from all timestamps then add it back to be pretty reliable in my experience.  `dateutil.parser.isoparser` uses similar logic for ISO time stamps with a 2400 hour. 

https://github.com/dateutil/dateutil/blob/296d419fe6bf3b22897f8f210735ac9c4e1cb796/src/dateutil/parser/isoparser.py#L136-L146

But I still don't understand what this fixed or what implications the fix has to the overall codebase.

@MikeNeilson I wish `%K` was a valid [`strftime`](https://strftime.org/) format

**Pull request merged**
